/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.nttdata.food.ordering.system.kafka.order.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum OrderApprovalStatusAvroModel implements org.apache.avro.generic.GenericEnumSymbol<OrderApprovalStatusAvroModel> {
  APPROVED, REJECTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderApprovalStatusAvroModel\",\"namespace\":\"com.nttdata.food.ordering.system.kafka.order.avro.model\",\"symbols\":[\"APPROVED\",\"REJECTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
