/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.nttdata.food.ordering.system.kafka.order.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum PaymentStatusAvroModel implements org.apache.avro.generic.GenericEnumSymbol<PaymentStatusAvroModel> {
  COMPLETED, CANCELLED, FAILED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentStatusAvroModel\",\"namespace\":\"com.nttdata.food.ordering.system.kafka.order.avro.model\",\"symbols\":[\"COMPLETED\",\"CANCELLED\",\"FAILED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
